### ISSUE TITLE
Error trying to use swappedDrops()

### ISSUE THREAD

**Issue by ONeillMB1** [MarioniLab/DropletUtils#10]
I get the following error when trying to use the swappedDrops() function.
`sPaths <- c("/Volumes/@home/scRNA/bin/cellRanger/pilot2/Pilot2Library1/outs/filtered_feature_bc_matrix.h5", "/Volumes/@home/scRNA/bin/cellRanger/pilot2/Pilot2Library2/outs/filtered_feature_bc_matrix.h5")`
`sD <- swappedDrops(sPaths)`

> HDF5-DIAG: Error detected in HDF5 (1.10.3) thread 0:
>   #000: H5D.c line 292 in H5Dopen2(): unable to open dataset
>     major: Dataset
>     minor: Can't open object
>   #001: H5Dint.c line 1205 in H5D__open_name(): not found
>     major: Dataset
>     minor: Object not found
>   #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
>     major: Symbol table
>     minor: Object not found
>   #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
>     major: Symbol table
>     minor: Object not found
>   #004: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
>     major: Symbol table
>     minor: Callback failed
>   #005: H5Gloc.c line 378 in H5G__loc_find_cb(): object 'barcode' doesn't exist
>     major: Symbol table
>     minor: Object not found
> Error in read10xMolInfo(samples[i], barcode.length = barcode.length) : 
>   c++ exception (unknown reason)

I've tried it on both the 'filtered_feature_bc_matrix.h5' and 'molecule_info.h5' files generated with cellRanger count (v 3.0.2) and get the same error. When I do the simulated reads as shown in the example everything works as expected.

**Comment by LTLA** [comment]
I daresay you're using _DropletUtils_ version 1.2.*. Only version 1.3.* supports the output from CellRanger version 3. Either install from Github or use BioC-devel.

**Comment by ONeillMB1** [comment]
You are correct that I am using DropletUtils version 1.2.2. 

When I try to install from Github I get an error.
```
> install_github("MarioniLab/DropletUtils")
Downloading GitHub repo MarioniLab/DropletUtils@master
Skipping 19 packages ahead of CRAN: beachmat, Biobase, BiocGenerics, BiocParallel, DelayedArray, edgeR, GenomeInfoDb, GenomeInfoDbData, GenomicRanges, HDF5Array, IRanges, limma, rhdf5, Rhdf5lib, S4Vectors, SingleCellExperiment, SummarizedExperiment, XVector, zlibbioc
✔  checking for file ‘/private/var/folders/5w/yj9ngl6s2z1fbzh9lv82p6dc0000gq/T/Rtmp3j25HW/remotes1010344790982/MarioniLab-DropletUtils-c366c58/DESCRIPTION’ ...
─  preparing ‘DropletUtils’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘DropletUtils_1.3.14.tar.gz’
   
* installing *source* package ‘DropletUtils’ ...
** libs
/usr/local/clang4/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/beachmat/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rhdf5lib/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/BH/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/dqrng/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c compute_multinom.cpp -o compute_multinom.o
compute_multinom.cpp:5:10: fatal error: 'beachmat/utils/const_column.h' file not found
#include "beachmat/utils/const_column.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [compute_multinom.o] Error 1
ERROR: compilation failed for package ‘DropletUtils’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/DropletUtils’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/DropletUtils’
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/5w/yj9ngl6s2z1fbzh9lv82p6dc0000gq/T//Rtmp3j25HW/file10103349f594c/DropletUtils_1.3.14.tar.gz' had non-zero exit status
```

I see that Bioconductor version '3.9' requires R version '3.6' for which the final release is 2019-04-26. Is there a workaround other than upgrading R?

**Comment by LTLA** [comment]
The official answer is no, you'll have to upgrade R to use the next version of _DropletUtils_. This is currently possible by using R-devel (which will become 3.6 at the end of April).

The unofficial answer is that you can install the latest _beachmat_ (v1.99.*) from Github, and then install _DropletUtils_ on top of that. This will get around _BiocManager_'s restrictions - but if you do this, be aware that this is an unsupported installation mode, so you had better know what you're doing.
