### ISSUE TITLE
Argument to use gene symbols or Ensembl IDs as row names in read10xCounts

### ISSUE THREAD

**Issue by lambdamoses** [MarioniLab/DropletUtils#101]
In Seurat, one can choose which column in the barcodes file to use as row names, and the default is the gene symbols. However, since Seurat doesn't have `rowData`, it's harder to trace duplicate gene symbols to the Ensembl ID. In scanpy, the gene symbols are used as row names while the Ensembl IDs are stored in the var metadata. I prefer to have Ensembl IDs behind the scene because one gene symbol can match multiple Ensembl IDs, but I prefer to show gene symbols in plots and results because gene symbols are more human readable. 

So is it possible to add an argument in `read10xCounts` to allow users to use gene symbols as row names and store Ensembl IDs in `rowData`? The default would still be Ensembl IDs so it won't break existing code of users. In case of duplicate gene symbols, use something like `scuttle::uniquifyFeatureNames` to append the Ensembl ID to disambiguate? This would be much nicer than manually calling `scuttle::uniquifyFeatureNames` and setting row names or using the `swap_rownames` argument in `scater` every single time.

**Comment by PeteHaitch** [comment]
Motivated by https://github.com/drisso/SingleCellExperiment/issues/70

**Comment by LTLA** [comment]
PR would be welcome, though I wouldn't want to introduce a hard dependency to **scuttle**.

**Comment by lambdamoses** [comment]
It's really easy to reimplement `scuttle::uniquifyFeatureNames` so no dependency is introduced. I can PR before the Bioc 3.18 release.
