### ISSUE TITLE
How to get the cell naems of those get filtered (considered as empty droplets)

### ISSUE THREAD

**Issue by grimwoo** [MarioniLab/DropletUtils#102]
Hi, I am using the seurat to process the data. And I wonder how to get the cell naems of those get filtered (considered as empty droplets), so that I could remove empty droplets in my seurat object (by ```subset(object = seurat.object, subset = CellNames %in% ???)```)

**Comment by jonathangriffiths** [comment]
Hi there,

Did you download the raw or processed data when you called the function?

If the default argument or `type=processed`, then you already have filtered cells.

Jonny.
