### ISSUE TITLE
Easiest way to convert read10xMolInfo data into a dataframe in R with gene labels as row names

### ISSUE THREAD

**Issue by sitapriyamoorthi** [MarioniLab/DropletUtils#104]
Hi, 
I have been playing around with the read10xMolInfo. 

What I am looking for is a simple solution wherein I can convert the .h5 file into an R data frame or data table and have gene names added as a separate column or as a row names. 

I see this feature may have been added to the counts function? 

Thanks

**Comment by sitapriyamoorthi** [comment]
I did this! Dont know if this is accurate mapping of gene names. Assuming the genes are indexed? This is in R.
```
mol.info <- read10xMolInfo(mol.info.file.h5)

mol.info.df <- mol.info$data %>% data.frame()

molecule.df.gene.name <- mol.info.df%>% 
	mutate(Gene = mol.info$genes[gene])
```

**Comment by jonathangriffiths** [comment]
While I'm not super fluent in tidyverse grammar, I think you have this right. As the man page for `read10xMolInfo` says, `mol.info$genes[gene]` should get you the vector of gene names/IDs.

Just a note for the future - if you ask on the Bioconductor support site, you'll likely get help faster, as more people than the package maintainer are watching. (Also, that's the canonically correct place for help, while this is the place for issues with the code or package not working as it is meant to)
