### ISSUE TITLE
Support for Droplet-Utils in Apple Silicon (ARM64)

### ISSUE THREAD

**Issue by mari-ga** [MarioniLab/DropletUtils#105]
Hi!

First of all, thank you very much for this wonderful tool. I was wondering if it is planned to add support for ARM64 processors for the conda package. Currently, the installation attempt for this package results in this error:

```
conda create -n dropletutils -c bioconda bioconductor-biobase
#conda answer on terminal:
Channels:
 - bioconda
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bioconductor-biobase

Current channels:

  - https://conda.anaconda.org/bioconda
  - defaults
  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Me and many people using this great package on Apple Silicon would be very grateful.

Thank you very much in advance!

**Comment by jonathangriffiths** [comment]
Hi,

Thanks for getting in touch.

There are a couple of challenges I have in answering this:
1. I don't control how conda manages Bioconductor packages - if you tried to install DropletUtils using the BiocManager framework (`BiocManager::install("DropletUtils")`), I'd wager it will install fine on Apple Silicon
2. The error message you are getting is about `bioconductor-biobase` - I don't have anything to do with Biobase, I'm afraid, so I am doubly-limited on resolving that for you

Jonny

**Comment by mari-ga** [comment]
Hi, thank you very much for your answer. I actually got it working on conda by following this tutorial for the use of different distributions of conda for Apple Silicon, here:[Tutorial for Conda X86_64 on Apple Silicon]( https://teamdynamix.umich.edu/TDClient/47/LSAPortal/KB/ArticleDet?ID=10245)
Having the version of conda for x86_64 running on Apple Silicon makes it possible to run this tool from conda.
It is probably a long road, but I leave it here, just in case it is useful for someone with this kind of problem :)

**Comment by LTLA** [comment]
FWIW BioC is close to getting binaries built for Arm Macs, I think **DropletUtils** had a successful build already (see [here](https://bioconductor.org/checkResults/release/bioc-mac-arm64-LATEST/DropletUtils/)) but I think they're just waiting on other packages before announcing its availability.
