### ISSUE TITLE
rowRanges Needs to be Manually Filled In

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/DropletUtils#106]
Could `read10xCounts` offer the convenience of recording row ranges to remove a step before `addPerCellQCMetrics` for mitochondrial content? A new parameter e.g. `GTFpath` could allow the user could specify e.g. `"refdata-gex-mm10-2020-A/genes/genes.gtf"`.

**Comment by LTLA** [comment]
IMO this seems out of scope  for `read10xCounts`. Unless the GTF is part of the CellRanger output directory (and I'm pretty sure it isn't), it shouldn't be `read10xCounts`'s job to pull in that information. 

But surely it's a one-liner that isn't too hard for users to write? Something like:

```r
rowRanges(sce) <- rtracklayer::import("my.gtf")[rownames(sce)]
```

**Comment by DarioS** [comment]
It is not part of the output directory, but in their standard GZip reference genome in `genes` folder as shown above.
