### ISSUE TITLE
Is downsampleMatrix necessary before empty cells detection?

### ISSUE THREAD

**Issue by tewengtong** [MarioniLab/DropletUtils#107]
Dear author,

I am trying to use DropletUtils to identify empty cells and ambient RNA. I follow this protocol: https://bioconductor.org/packages/release/bioc/vignettes/DropletUtils/inst/doc/DropletUtils.html#detecting-empty-droplets. My question is: Do I need to perform downsampling before detecting empty cells/ambient RNA? My data is 8 samples pooling in one library.

Thank you!

**Comment by jonathangriffiths** [comment]
Treat each 10X sample separately; though there is no need to downsample. It's important to run separately because the "soup" should be unique to each sample.

Please ask support questions in support.bioconductor.org in future too
