### ISSUE TITLE
read10xCounts Won't Import a Public Dataset

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/DropletUtils#112]
I downloaded one triplet from [GSE146974](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146974).

```r
> dir()
"GSM4411625_barcodes_MH001.tsv.gz" "GSM4411625_genes_MH001.tsv.gz"    "GSM4411625_matrix_MH001.mtx.gz"

> read10xCounts("./GSM4411625").
Error in .check_for_compressed: cannot find './GSM4411625/barcodes.tsv' or its gzip-compressed form
```

It is not treating the user specification as a prefix.

So, I downloaded the remaining samples and put them into separate folders and renamed each of the files using `mv`.

```
$ ls *
MH001:
barcodes.tsv.gz  genes.tsv.gz  matrix.mtx.gz
RP002:
barcodes.tsv.gz  genes.tsv.gz  matrix.mtx.gz
RP009:
barcodes.tsv.gz  genes.tsv.gz  matrix.mtx.gz
```

Trying to use `read10xCounts` again, but no success.

```r
folders <- c("MH001", "RP002", "RP009")
monocytes <- read10xCounts(folders, folders)
Error in validObject(.Object) : 
  invalid class “SummarizedExperiment” object: 
    'x@assays' is not parallel to 'x'
```

**Comment by LTLA** [comment]
In the first case, the prefix is not recognized as there's some `_MH001` gunk at the end that interferes with matching of the names. And besides, even if there wasn't that suffix, your prefix is wrong; it's actually `GSM4411625_`.

Dunno about the second error. Seems like there's something wrong with your files.

**Comment by jonathangriffiths** [comment]
These seem to be masquerading as 10x files but they are not. For example, the MH001 barcodes reads:
```
batch_label     cellname        dataset_batch   dataset_label   status_label    n_genes n_counts        percent_mito
2017_0801       CTCTACGCACAGACAG-1-MH001        MH001   MH001   Healthy 642     1398.0  0.03576538
2017_0801       ACGCCAGAGATGTAAC-1-MH001        MH001   MH001   Healthy 1474    5228.0  0.046289213
2017_0801       AGAGTGGGTATAGTAG-1-MH001        MH001   MH001   Healthy 980     2694.0  0.024127692
2017_0801       GTATCTTCATCGGAAG-1-MH001        MH001   MH001   Healthy 1750    6304.0  0.036326144
2017_0801       AACCGCGGTGCGGTAA-1-MH001        MH001   MH001   Healthy 2996    13008.0 0.036131613
```

There is a similar situation with the genes.

I did not design this part of the package but I think this function is only meant to be run on real 10x output data, which this is not.
