### ISSUE TITLE
riscv64 test Failure ('test-hashing.R:244:9'): edge cases are handled correctly with combinatorial barcodes

### ISSUE THREAD

**Issue by mr-c** [MarioniLab/DropletUtils#113]
Hello,

In Debian, we have a single test failing on riscv64
```
── Failure ('test-hashing.R:244:9'): edge cases are handled correctly with combinatorial barcodes ──
 out$LogFC not identical to .compute_expected_lfc(SCALING, PSEUDO).
 Objects equal but not identical
```

We could patch the test to use `expect_equal` instead of `expect_identical`, but I wanted to check here first to see if that was okay

**Comment by LTLA** [comment]
Yeah, we should probably change it to `expect_equal()`. I don't think floating-point identity is a requirement of that particular test.

**Comment by mr-c** [comment]
@LTLA Thanks, we'll do that.

**Comment by jonathangriffiths** [comment]
Thanks both for the work on this!
