### ISSUE TITLE
10X vs MGI single cell empty droplets identification

### ISSUE THREAD

**Issue by Rohit-Satyam** [MarioniLab/DropletUtils#115]
Dear @LTLA 

Greetings. I have been using your `emptyDrops` function for two years and it has served me well for our parasite-related single-cell data. Recently, we decided to switch to MGI single cell. We sequenced the same kind of control and KO samples highly synchronized at the same time point as we did for 10X and sequenced them using MGI and we see the following plot:
![barcoderank_plot](https://github.com/user-attachments/assets/55c06121-8129-4136-bf87-5e38e954289e)

The Knee Point for MGI samples are higher than they should be. I used the following code to make the graph

```r
## Barcode_data contains results from barcodeRanks and barcode_points contains the knee point obtained from barcodeRanksRes@metadata$inflection

ggplot(data = barcode_data, aes(x = rank, y = total)) +
    geom_point(aes(colour = .id )) +
    geom_hline(data = barcode_points[c(2,4,6,8),],
               aes(yintercept = value,
                   colour = type), linetype = 2) + geom_hline(yintercept=1000, linetype="dashed", color = "black",linewidth=1.5)+
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x))) +
    scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x))) +
    labs(title = paste0("Waterfall plot of read counts (log)"),
         x = "Log Rank",
         y = "Log counts")+
  theme_minimal()+
  theme(axis.text.x = element_text(face="bold", color="black", size=12),axis.text.y = element_text(face="bold", color="black", size=12),text = element_text(face="bold",color="black",size = 12),legend.title = element_text(face="bold",color="black",size = 12),legend.text = element_text(face = "bold",color = "black",size = 12))
p <- p+ggsci::scale_color_aaas()

```
![image](https://github.com/user-attachments/assets/69264fca-4779-4dc2-b580-170edbaab889)

Note: We expect 10K cells. 

Below is what MGI shared with us:

![image](https://github.com/user-attachments/assets/d2604d0a-fd9f-4512-b067-338f95418690)

**Comment by LTLA** [comment]
Nothing comes to mind. Perhaps you could try increasing with `exclude.from=` in `barcode.args=` if the knee point is incorrectly located at the unstable low-density part of the curve.

Truth be told, most of your knee point locations look kind of strange. Only the blue one looks somewhat okay. If you post an RDS with the column sums for each sample, I could have a look.

**Comment by Rohit-Satyam** [comment]
Here are the R objects: https://file.io/kqAxPlIR0h8v available for 2 weeks. The 10X data is from our paper [here](https://www.nature.com/articles/s41564-023-01497-6). We prepared fresh cells for MGI using the same clones and procedure we used for 10X.

**Comment by Rohit-Satyam** [comment]
I just realised that the MGI pipeline was filtering out non coding RNA (tRNA and rRNA and other) so think it has to to do something with that. I will rerun everything @LTLA. I will rerun Droplet detection again and reshare the objects. Apologies, I know your time is valued and wanted to inform you.

**Comment by Rohit-Satyam** [comment]
I reran the MGI count pipeline again and revised the plots but the issue persists. [Here](https://drive.google.com/file/d/1XNVi9bB9WaHKuS_5sUp5pAtSzk7NsGIA/view?usp=sharing) is the revised RDS file. The revised plot is also attached:

![image](https://github.com/user-attachments/assets/b340e43d-909f-4e6b-adb8-0e1adea58b1e)

**Comment by LTLA** [comment]
For starters, the colors on your points and lines don't match for the 10X samples.

Anyway, the problem is the instability of the first/second derivatives of the curve on empirical data, which means that there are multiple local optima in the curvature (which is ultimately used to define the knee point). IIRC this has been a theoretical problem for a long time but the results were usually okay so I just left it as-is.

I've created the `improved-knee` branch that uses a more stable algorithm for knee point identification. You can try installing it and see if it gives better results. (Dashed line below is the knee, dotted is inflection.)

```r

library(SingleCellExperiment)
data <- readRDS("all_SCE_objs.rds")
library(DropletUtils)
out <- lapply(data, function(x) barcodeRanks(assay(x)))

par(mfrow=c(2,2))
for (n in names(out)) {
    current <- out[[n]]
    o <- order(current$rank)
    plot(current$rank[o], current$total[o], log="xy", type="l", main=n)
    abline(h=metadata(current)$knee, lty=2)
    abline(h=metadata(current)$inflection, lty=3)
}
```

![test](https://github.com/user-attachments/assets/a2a54496-8d6a-453e-9ad5-93a487ebf0d3)

**Comment by Rohit-Satyam** [comment]
Thanks @LTLA. The knee point has improved. It further improves when I set `exclude.from=100` or `exclude.from=1000` the dashed line visually could be seen closer to the knee point.

**Comment by LTLA** [comment]
I probably wouldn't spend too much time fiddling with the parameters. The knee point is mostly a visual artifact, the position of which will depend on the scaling of the plot - see the criticisms in the [Wikipedia article](https://en.wikipedia.org/wiki/Knee_of_a_curve).
