### ISSUE TITLE
`emptyDrops` gives less number of Cells as compared to `emptyDropsCellRanger` or `defaultDrops`

### ISSUE THREAD

**Issue by Rohit-Satyam** [MarioniLab/DropletUtils#116]
Dear @LTLA 

Sorry to bug you again. We got another single cell for another parasite Toxoplasma and we were calculating the capture rate. We have seen in past that `emptyDrops` methods rescues more cells as compared to `emptyDropsCellRanger` or `defaultDrops` as per your explanation [here](https://github.com/MarioniLab/DropletUtils/issues/42) and [here](https://github.com/MarioniLab/DropletUtils/issues/33#issuecomment-578206745). This is true for plasmodium data so far. However, we are getting the opposite for this parasite data from Toxoplasma. Our Input cells were ~30K. Since this is unpublished data (except 10X Ctrl which is from [literature](https://www.nature.com/articles/s41467-024-51011-7#data-availability) having the same strain as we are using, but they expected to recover 10K cells), I will have to check with my boss first if we can share it with you. Until then is there anything that comes to mind? 

| Samples              | emptyDrops | emptyDropsCellRanger(expected=30K) | defaultDrops(expected 30K) | MGI (Python implementation of emptyDropsCellranger.R) |
| -------------------- | ---------- | ---------------------------------- | -------------------------- | ------------------------- |
| Public Control 10X   | 8949       | 13016                              | 13013                      | \-                        |
| In-house Control MGI | 15947      | 25357                              | 25317                      | 19216                     |
| In-house KO          | 18975      | 27821                              | 27501                      | 20603                     |

Code used are

```r
empty_filt <- function(sceobj){
  e.out <- emptyDrops(counts(sceobj),retain = Inf)
  #e.out <- emptyDrops(counts(sceobj))
  sceobj <- sceobj[,which(e.out$FDR <= 0.01)]
  return(sceobj)}

empty_filtCR <- function(sceobj,ncell=30000){
  e.out <- emptyDropsCellRanger(counts(sceobj),n.expected.cells =ncell)
  #e.out <- emptyDrops(counts(sceobj))
  sceobj <- sceobj[,which(e.out$FDR <= 0.01)]
  return(sceobj)}

empty_filtbc <- function(sceobj,ncell=30000){
  e.out <- defaultDrops(counts(sceobj),expected =ncell)
  #e.out <- emptyDrops(counts(sceobj))
  sceobj <- sceobj[,e.out]
  return(sceobj)}
```

**Comment by Rohit-Satyam** [comment]
Hi @LTLA. I discussed with my PI and we can share the RDS file with you if you require it.

**Comment by LTLA** [comment]
Based on your table above, the answer is pretty clear - the increased identification is being driven by the choice of the "first subset" in `emptyDropsCellRanger` (see Details in `?emptyDropsCellRanger`). Barcodes in the first subset are assumed to be real cells, regardless of their expression profile. Identification of the first subset is very closely related to the `defaultDrops` algorithm and you can see how well the numbers match up between `defaultDrops` and `emptyDropsCellRanger` in your table. By comparison, I suspect that `emptyDrops` has a much more conservative threshold for "assumed real cells" based on the knee point, so it doesn't get the free ride that CellRanger gets.
