### ISSUE TITLE
`barcodeRanks` input matrix description

### ISSUE THREAD

**Issue by kevinwang09** [MarioniLab/DropletUtils#16]
Hi Aaron, 

In the documentation of the `barcodeRanks`, it said that the input matrix, `m`, should have "Columns represent barcoded droplets, rows represent cells". 

Is this a typo that the columns should be "genes" and rows are cells (or the other way around) Or have I misunderstood this function and it expects a cell-filtered data as the input?

Many thanks, 
Kevin

**Comment by LTLA** [comment]
Well spotted. Your first interpretation is correct.
