### ISSUE TITLE
How to use with Seurat raw data

### ISSUE THREAD

**Issue by cswoboda** [MarioniLab/DropletUtils#19]
Hello MarioniLab!

We've seen some pretty extreme ambient RNA effects in our data, but when I enter my dgCMatrix, I get this error:

testEmptyDrops(fivemonth.data, lower=100, niters=10000, test.ambient=FALSE, ignore=NULL, alpha=NULL, BPPARAM=SerialParam()) 

"Error in testEmptyDrops(fivemonth.data, lower = 100, niters = 10000, test.ambient = FALSE,  : 
  no counts available to estimate the ambient profile"

I'm running on windows in RStudio with R 3.6.1.

Hope you can help and thanks for reading this!

Casey

**Comment by LTLA** [comment]
See https://support.bioconductor.org/p/123554/#123562.

**Comment by LTLA** [comment]
I'll assume that the explanation in the post was clear enough.
