### ISSUE TITLE
From DropletUtils to Seurat

### ISSUE THREAD

**Issue by LuciaJim** [MarioniLab/DropletUtils#21]
Hi Aaron,
I've use DropletUtils to filtrate my single cell data coming from STARsolo.
I would like to proceed to Seurat, however I don't know how to obtain the filtrated matrix.mtx, barcodes.tvs and genes.tvs for this purpose.

I've loaded the unfiltered matrix.mtx, barcodes.tvs and genes.tvs, I've performed read10xCounts to pull this data together, then barcodeRanks and finally emptyDroplets. The final output I got is the is.cell logical as it's explained in Utilities for handling droplet-based single-cell RNA-seq data from Bioconductor.

> 

         is.cell <- e.out$FDR <= 0.01
         sum(is.cell, na.rm=TRUE)

What am I missing?

Thank you for your time!

Best,
Lucia

**Comment by LTLA** [comment]
Not sure I understand your problem. Why don't you just subset the count matrix by `is.cell`?

**Comment by LuciaJim** [comment]
Hi Aaron,
Sorry, I'm new into programming and r. 
I've finally been able to create a table only with the is.cell barcodes and subsample the sparse matrix with them.
 > 

        is.cell2 <- tidyr::replace_na(data = is.cell, FALSE)
        barcodes.filtered <- barcodes[is.cell2,]
        P.data <- Read10X(data.dir = "~/Desktop/")
        Psubset <- P.data[,barcodes.filtered]

Is this what you mean?

Best,
Lucia

**Comment by LTLA** [comment]
No need for `tidy::replace_na`. Just use `which()`, as described in the workflow.

```r
filtered.counts <- counts(sce)[,which(is.cell)]
```

There, that's the count matrix - nice and easy, no need to re-read it in with `Read10X`. If you want to use Seurat, just use the Seurat object constructor. Or you can just proceed with the rest of the analysis in the workflow, it's more or less the same anyway.

**Comment by LuciaJim** [comment]
Great! Thank you for the help and for the book.
Best,

Lucía
