### ISSUE TITLE
Is it necessary to run testEmptyDrops prior to emptyDrops?

### ISSUE THREAD

**Issue by lc822** [MarioniLab/DropletUtils#23]
Hi,

Looking at the documentation for the emptyDrops function, I am confused as to whether it is necessary to perform "testEmptyDrops" prior to running "emptyDrops"?  From the example, it doesn't seem as though this is necessary but then the information says that emptyDrops uses the results from testEmptyDrops?

"The emptyDrops function combines the results of testEmptyDrops with barcodeRanks to identify droplets that are likely to contain cells"

I would appreciate your clarification on this.

Many thanks,
Lucy

**Comment by LTLA** [comment]
No, it's not necessary, `emptyDrops` calls `testEmptyDrops` internally. The functions are split into two in order to allow developers (not users) to call `testEmptyDrops` without having to run `barcodeRanks` if they don't care about it.

I guess this could be clarified in the documentation.

**Comment by lc822** [comment]
Great, thank you.
