### ISSUE TITLE
Installation under BioC docker

### ISSUE THREAD

**Issue by kevinwang09** [MarioniLab/DropletUtils#25]
I am trying to install this package in the Docker image from `bioconductor/devel_core2:20190919` using `BiocManager::install("DropletUtils")`. But this installation failed.

The installation message of this package and the sessioninfo outputs are here: https://gist.github.com/kevinwang09/d65d57cf9d2c4ed8238bb648eb570f94

Any suggestions?
Thanks, Kevin

**Comment by LTLA** [comment]
I dunno, looks like a _Rhdf5lib_ problem to me. Tagging @grimbough.

**Comment by grimbough** [comment]
Sorry. Hopefully fixed in #26

**Comment by kevinwang09** [comment]
It worked! Like magic! I will close the issue.
