### ISSUE TITLE
Error in testEmptyDrops(m, lower = lower, ...) :    no counts available to estimate the ambient profile

### ISSUE THREAD

**Issue by Janexty** [MarioniLab/DropletUtils#29]
Hi Aaron,
    I use the DropletUtils  package to filter single cell data.
    I have encountered this problem .

   `tmpdir = setwd("F:/sample208_filtered_feature_bc_matrix")  `
   `dir.name <- tmpdir`
  ` list.files(dir.name)`
"barcodes.tsv" "genes.tsv"    "matrix.mtx"
 
`sce <- read10xCounts(dir.name,col.names = TRUE)`
 ` sce`
 class: SingleCellExperiment 
dim: 32738 11701 
metadata(0):
assays(1): counts
rownames(32738): ENSG00000243485 ENSG00000237613 ... ENSG00000215616
  ENSG00000215611
rowData names(3): ID Symbol NA
colnames(11701): AAACCCAAGACAAGCC-1 AAACCCAAGCTGTACT-1 ... TTTGTTGTCGATACGT-1
  TTTGTTGTCTCTGACC-1
colData names(2): Sample Barcode
reducedDimNames(0):
spikeNames(0):

`set.seed(100) `
`e.out <- emptyDrops(counts(sce))`
Error in testEmptyDrops(m, lower = lower, ...) : no counts available to estimate the ambient profile

I don't know this problem about relativing "rowData names(3):ID Symbol NA"  

I will appreciate any advice on how to solve this.
Many thanks
Janexty

**Comment by LTLA** [comment]
Have a look at #14 and https://support.bioconductor.org/p/123554/#123562.

**Comment by Janexty** [comment]
Yes, thank you very much.

**Comment by LTLA** [comment]
I'm going to assume that this was resolved.

**Comment by hk20013106** [comment]
Hi I'm having the same issue and I'm using the BD Rhapsody scRNA data. 
I'm using the matrix which I assume is the raw. 
So what should I do now? 

Thanks!

**Comment by LTLA** [comment]
Please open a new issue.
