### ISSUE TITLE
cannot install this packages???

### ISSUE THREAD

**Issue by pangxueyu** [MarioniLab/DropletUtils#3]
my codes are under following:

> library(githubinstall)
> githubinstall("DropletUtils")
Suggestion:
 - MarioniLab/DropletUtils  Package for handling droplet-based single-cell RNA-seq data
Do you want to install the package (Y/n)?  Y
Installing "DropletUtils" package from GitHub, but already installed from unknown repository.
This package is already installed. Are you sure you want to overwrite it (Y/n)?  y
Downloading GitHub repo MarioniLab/DropletUtils@master
from URL https://api.github.com/repos/MarioniLab/DropletUtils/zipball/master
Installing DropletUtils
'/mnt/data/program/R-3.5.0/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpmgESir/devtools35404cb6b249/MarioniLab-DropletUtils-cec27d4'  \
  --library='/mnt/data/program/R-3.5.0/library' --install-tests

* installing *source* package ‘DropletUtils’ ...
** libs
g++ -std=gnu++11 -I"/mnt/data/program/R-3.5.0/include" -DNDEBUG  -I"/mnt/data/program/R-3.5.0/library/Rcpp/include" -I"/mnt/data/program/R-3.5.0/library/beachmat/include" -I"/mnt/data/program/R-3.5.0/library/Rhdf5lib/include" -I/usr/local/include   -fpic  -g -O2 -c compute_multinom.cpp -o compute_multinom.o
compute_multinom.cpp: In instantiation of ‘SEXPREC* compute_multinom_internal(MAT, SEXP) [with V = Rcpp::Vector<13>; MAT = beachmat::lin_matrix<int, Rcpp::Vector<13> >*; SEXP = SEXPREC*]’:
compute_multinom.cpp:35:78:   required from here
compute_multinom.cpp:16:61: error: ‘class beachmat::lin_matrix<int, Rcpp::Vector<13> >’ has no member named ‘get_const_col_indexed’
         auto info=M->get_const_col_indexed(c, target.begin());
                                                             ^
compute_multinom.cpp: In instantiation of ‘SEXPREC* compute_multinom_internal(MAT, SEXP) [with V = Rcpp::Vector<14, Rcpp::PreserveStorage>; MAT = beachmat::lin_matrix<double, Rcpp::Vector<14, Rcpp::PreserveStorage> >*; SEXP = SEXPREC*]’:
compute_multinom.cpp:38:78:   required from here
compute_multinom.cpp:16:61: error: ‘class beachmat::lin_matrix<double, Rcpp::Vector<14, Rcpp::PreserveStorage> >’ has no member named ‘get_const_col_indexed’
/mnt/data/program/R-3.5.0/etc/Makeconf:168: recipe for target 'compute_multinom.o' failed
make: *** [compute_multinom.o] Error 1
ERROR: compilation failed for package ‘DropletUtils’
* removing ‘/mnt/data/program/R-3.5.0/library/DropletUtils’
* restoring previous ‘/mnt/data/program/R-3.5.0/library/DropletUtils’
Installation failed: Command failed (1)
Warning message:
In fread(download_url, sep = "\t", header = FALSE, stringsAsFactors = FALSE,  :
  Found and resolved improper quoting out-of-sample. First healed line 4848: <<Puriney  honfleuR        "Evening, honfleuR" by Seurat>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.

how should I to re-try?

**Comment by LTLA** [comment]
Follow the installation instructions on Bioconductor:

https://www.bioconductor.org/packages/release/bioc/html/DropletUtils.html

We are currently on Bioconductor version 3.7. If your _BiocInstaller_ is not v1.30.0, please read:

https://www.bioconductor.org/install/
