### ISSUE TITLE
read10xCounts If Single Directory

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/DropletUtils#32]
Often, data obtained from GEO Browser will be a TAR file of all of the samples' files. For example,

```
$ ls | head
GSE139324_RAW.tar
GSM4138110_HNSCC_1_PBMC_barcodes.tsv.gz
GSM4138110_HNSCC_1_PBMC_genes.tsv.gz
GSM4138110_HNSCC_1_PBMC_matrix.mtx.gz
GSM4138111_HNSCC_1_TIL_barcodes.tsv.gz
GSM4138111_HNSCC_1_TIL_genes.tsv.gz
GSM4138111_HNSCC_1_TIL_matrix.mtx.gz
GSM4138112_HNSCC_2_PBMC_barcodes.tsv.gz
GSM4138112_HNSCC_2_PBMC_genes.tsv.gz
GSM4138112_HNSCC_2_PBMC_matrix.mtx.gz
```

But from the description of `samples`, `read10xCounts` requires that each sample be in a separate folder. Could it be modified so that it works easily with data obtained from GEO Browser?

**Comment by LTLA** [comment]
A PR would be welcome.

In terms of implementation, I would suggest supplying _prefixes_ of the files in `samples=`, and then just adding a `"prefix"` option in `type`. In your case, the call would be something like:

```r
# Can also get this by unique(sub("_[^_]+$", "", list.files()))
read10xCounts(
    c(
        "GSM4138110_HNSCC_1_PBMC_", 
        "GSM4138111_HNSCC_1_TIL_",
        "GSM4138112_HNSCC_2_PBMC_"
    ),
    type="prefix"
)
```

This would involve less modification of code and complexity than introducing a new argument.

**Comment by DarioS** [comment]
I understand that existing users would not want the order of parameters to change if they are using positional argument matching. The change you suggest adds modifies what `type` means which associates it to `samples` whereas currently it has no association to `samples`. For consistency, perhaps it is best that I simply reorganise the files using `strsplit`, `dir.create` and `fs::file_move`.

**Comment by LTLA** [comment]
I don't think there's any problem. `type` just indicates how each entry of `samples` should be interpreted. Each prefix represents a sample and is perfectly suited to be an entry of `samples`. I mean, even now, the function will try to auto-guess `type` based on each entry of `samples`, so the two are hardly independent.

**Comment by DarioS** [comment]
Alright, I'll make the changes in a few days.

**Comment by DarioS** [comment]
But, how would the user then specify the data type explicitly? If they have sparse data, they might need to do `type = c("prefix", "sparse")` but that would require the function's code `type <- match.arg(type)` to be changed to something more complicated, depending on if the user set `type` to one value or two values.

**Comment by LTLA** [comment]
`"prefix"` implies `"sparse"`, it's just a change in how the paths are assembled. There wouldn't be a case where `"prefix"` needs to be used with `"HDF5"` because in the latter you would just pass the path to the HDF5 file for each sample directly.

**Comment by DarioS** [comment]
The function `.read_from_sparse` has 

```r
    if (version=="3") {
        bname <- "barcodes.tsv.gz"
        gname <- "features.tsv.gz"
        mname <- "matrix.mtx.gz"
    } else {
        bname <- "barcodes.tsv"
        gname <- "genes.tsv"
        mname <- "matrix.mtx"
    }
```

but the data I downloaded has file names like GSM4138110_HNSCC_1_PBMC_barcodes.tsv.gz, GSM4138110_HNSCC_1_PBMC_genes.tsv.gz, GSM4138110_HNSCC_1_PBMC_matrix.mtx.gz So, it's a bit like version 2 (genes, not features) and a bit like version 3 (compressed). The genes table has two columns

```
$ gunzip -c GSM4138110_HNSCC_1_PBMC_genes.tsv.gz | head -n 5
ENSG00000243485 RP11-34P13.3
ENSG00000237613 FAM138A
ENSG00000186092 OR4F5
ENSG00000238009 RP11-34P13.7
ENSG00000239945 RP11-34P13.8
```

so, it seems more like version 2.

```r
    if (version=="3") {
        colnames(gene.info) <- c("ID", "Symbol", "Type")
    } else {
        colnames(gene.info) <- c("ID", "Symbol")
    }
```

Shall I re-write this substantially, like `gname <- list.files(pattern ="(genes|features).tsv*")` for example and delete the first if statement shown above altogether? I have never done a single cell analysis before this one I'm attempting with public data, so my intuition about the file formats is non-existent. Also, I don't know if `if (file.exists(file.path(path, "features.tsv.gz"))) "3" else "2"` is still relevant or if I should change it to something else during my edits.

**Comment by LTLA** [comment]
Okay. Hm. This ended up being more complicated than I thought, and it was easier to show than tell, so I just went ahead and did it myself. Have a look at the `prefixes` branch and see whether it meets your needs; you should be able to do:

```r
library(DropletUtils)
sce <- read10xCounts(
   c("GSM4138110_HNSCC_1_PBMC_", "GSM4138111_HNSCC_1_TIL_"),
   type="prefix")
```

Still needs some tests in `tests/testthat/test-read10x.R`, so you can chip in with some if you like. Or not, I'll get to it eventually.

**Comment by LTLA** [comment]
That's the thing, it should be able to detect that. I mean, literally running my code snippet in the directory after unpacking the RAW tarball from GEO works for me:

```r
library(DropletUtils)
sce <- read10xCounts(
   c("GSM4138110_HNSCC_1_PBMC_", "GSM4138111_HNSCC_1_TIL_"),
   type="prefix")
sce
## class: SingleCellExperiment 
## dim: 33694 3023 
## metadata(1): Samples
## assays(1): counts
## rownames(33694): ENSG00000243485 ENSG00000237613 ... ENSG00000277475
##   ENSG00000268674
## rowData names(2): ID Symbol
## colnames: NULL
## colData names(2): Sample Barcode
## reducedDimNames(0):
## spikeNames(0):
## altExpNames(0):
```

**Comment by DarioS** [comment]
Works for me, too. I had one file that was both zipped and unzipped because I extracted it during testing to explore it, which was causing my obscure problem.
