### ISSUE TITLE
Change inflection point, maintaining the knee

### ISSUE THREAD

**Issue by LuciaJim** [MarioniLab/DropletUtils#33]
Hi Aaron,

This is the usual appearance of the barcodeRanks plot of my single-cell datasets when I apply the default features of barcodeRanks:
![barcodeRanks plot](https://user-images.githubusercontent.com/55449383/72977956-d63ef500-3dd5-11ea-9285-b275746f46e9.png)

However there is a precise batch in which the inflection point includes many more cells than before, going up to the second "knee" that my data has:
![barcodeRanks plot](https://user-images.githubusercontent.com/55449383/72978199-477ea800-3dd6-11ea-892b-091766f516aa.png)

Would it be posible to restrict the inflection point to the first knee as before without changing the knee point? I've modified barcodeRanks parameters such as df and fit.bounds, however I only managed to change the spline or move the knee point to the second knee rather than restrict the inflection point.

Thank you for your help.

Best,
Lucia

**Comment by LTLA** [comment]
I guess the function could be modified to include some kind of `inflection.bounds` argument. I would be willing to entertain a PR to that effect; it would basically need to restrict the definition of `right.edge` to only use `d1n` for `x` within `inflection.bounds`. (Note that, for simplicity, the value of the numerical derivative is assigned to the left point.)

**Comment by LuciaJim** [comment]
Hi Aaron,
I'm in the process of re-conversion to bioinformatician so I'm a bit lost in terms of modifying the code to include this new argument. Can you elaborate a bit more on how can this be done? I'll try to do my best!

In any case, if I understood well, in the barcodeRanks plot the red line that goes down to the inflection point represents the barcodes (or cells) that will be consider as non-empty droplets. Is it right? Thus, I thought that by being more strict in the lower argument from barcodeRanks that would solve my problem:
```br.out <- DropletUtils::barcodeRanks(new.counts, lower=200)```

Indeed it worked for the appearance of the plot:
![barcodeRanks plot_BRlower=200](https://user-images.githubusercontent.com/55449383/73060249-b5d76f00-3e97-11ea-9875-01696e131eb3.png)
However, the number of non-empty droplets didn't change and was still nonsense (this is 10X data and I aimed a maximum cell recovery of 10K):
For CellRanger cell call
```set.seed(100)
called <- defaultDrops(new.counts)
table(called)
cell.counts <- new.counts[, called]
called
 FALSE   TRUE 
727055  10225 
```
And for empty droplets
```set.seed(100)
e.out <- emptyDrops(new.counts)
is.cell <- e.out$FDR <= 0.01
sum(is.cell, na.rm=TRUE)
[1] 18298
table(Limited=e.out$Limited, Significant=is.cell)
       Significant
Limited FALSE  TRUE
  FALSE 44749  8776
  TRUE      0  9522
```
I guess that in order to have a  more realistic output of the number of cells I should change the code from emptyDroplets and not barcodeRanks.

Sorry for the long message.
Any help will be more than welcome!

Lucia

**Comment by LTLA** [comment]
> In any case, if I understood well, in the barcodeRanks plot the red line that goes down to the inflection point represents the barcodes (or cells) that will be consider as non-empty droplets. Is it right?

The inflection point has very little contribution to the cell calling. The inflection point is only used to restrict the range of x-coordinates used to find the knee point; it is the knee point that is used as `retain` in the `emptyDrops()` call. So fiddling with the inflection point won't have an effect if it doesn't change the knee point, which looks to be a reasonable choice anyway.

> However, the number of non-empty droplets didn't change and was still nonsense

Those are some strong words there. You better be prepared to back them up.

The novelty of `emptyDrops()` is that it is able to recover cell types from low-count libraries that people were previously throwing out. So, yes, you will get more cell calls from `emptyDrops()` - often a lot more - because that's the whole idea! 

To me, complaints about an unexpected number of cells are equivalent to complaints about "not getting any DE genes" for bulk RNA-seq analyses. Unless there is compelling evidence to the contrary, it is almost always a case of "it's not the method, it's your data". The most obvious explanation is that you simply captured cells at a higher efficiency, I can't imagine that you literally put in 10000 cells and expected to get all of them back out again.

Another explanation is that you are capturing cell fragments in a large number of droplets. I am somewhat sympathetic to users encountering this problem, but again, `emptyDrops()` is not technically wrong here; these droplets are not _empty_, after all, and there is a fine line between a damaged cell and a cell fragment. (If we removed cells with any damage, we would never get any neurons, for example.) This is a more arbitrary decision that requires post-calling QC to clean up. 

For comparison, it would be prudent to understand how `defaultDrops()` works. If you read the documentation, you will see that `defaultDrops()` requires an `expected=` argument, indicating the number of cells you expect to get in your experiment. You will see that the default value is 3000, meaning that in your analysis above, you are expecting 3000 cells but getting 10000! So by your standards, that doesn't make much sense either.

If you want to convince me that `emptyDrops()` is not doing the right thing, you should show that the extra retained droplets are actually empty droplets and not any biological subpopulation. A histogram like that in [Figure 6.6](https://osca.bioconductor.org/quality-control.html#testing-for-empty-droplets) would also be necessary.

**Comment by LuciaJim** [comment]
Hi Aaron,

Thank you for the information and help. This is helping me a lot to clarify my analysis. I never meant to give the idea that there was a problem with the method, but with my sample and the parameters I was applying (as it didn’t have the quality that the previous samples I got in the past had). The strong words come from the information I got from 10XGenomics in which they say that you could aim no more than 10K cells per sample run. I agree with you that for sure there is a great probability of loosing cells during the whole pipeline. Actually, what you load in the chip in order to get those 10K cells is about 17400 cells. I would like to think that the cell recovery was perfect, however I had some doubts.  After checking the distribution of p-values for the assumed empty droplets, as well as the number of counts, features and percentage of mitochondrial genes, it doesn´t look extreme so it can be used for subsequent analysis:
![p-values distribution for empty droplets](https://user-images.githubusercontent.com/55449383/73136286-36d76780-404c-11ea-8714-354a3be6b569.png)
![features_counts_MT](https://user-images.githubusercontent.com/55449383/73136287-39d25800-404c-11ea-828d-987b8e12c315.png)


I’ve continued checking other new samples I have and I would love to have your opinion about this other three cases. 
Case 1 and case 2 both have a reasonable knee point, however the number of non-empty droplets is simply huge: 
Case1:
![barcodeRanks plot](https://user-images.githubusercontent.com/55449383/73136533-ef9ea600-404e-11ea-9923-8d6667d291ba.png)
```
set.seed(100)
called <- defaultDrops(new.counts, expected=9000)
table(called)
cell.counts <- new.counts[, called]
called
  FALSE    TRUE 
6789711    5169 
```
```
set.seed(100)
e.out <- emptyDrops(new.counts)
is.cell <- e.out$FDR <= 0.01
sum(is.cell, na.rm=TRUE)
[1] 34264
table(Limited=e.out$Limited, Significant=is.cell)
       Significant
Limited FALSE  TRUE
  FALSE 41202 18633
  TRUE      0 15631
```
![p-values distribution for empty droplets](https://user-images.githubusercontent.com/55449383/73136715-00e8b200-4051-11ea-9e29-ed97920c1a5e.png)
![features_counts_MT](https://user-images.githubusercontent.com/55449383/73136718-05ad6600-4051-11ea-95e3-e650745994e8.png)


Case2:
![barcodeRanks plot](https://user-images.githubusercontent.com/55449383/73136539-ffb68580-404e-11ea-8195-6e0ce54f88f8.png)
```
set.seed(100)
called <- defaultDrops(new.counts, expected=9000)
table(called)
cell.counts <- new.counts[, called]
called
  FALSE    TRUE 
6788487    6393 
```
```
set.seed(100)
e.out <- emptyDrops(new.counts)
is.cell <- e.out$FDR <= 0.01
sum(is.cell, na.rm=TRUE)
[1] 62782
table(Limited=e.out$Limited, Significant=is.cell)
       Significant
Limited FALSE  TRUE
  FALSE 11003 10317
  TRUE      0 52465
```
![p-values distribution for empty droplets](https://user-images.githubusercontent.com/55449383/73136754-80768100-4051-11ea-8961-c88d81fba7a7.png)
![features_counts_MT](https://user-images.githubusercontent.com/55449383/73136757-84a29e80-4051-11ea-9fc6-026a58a8f753.png)


Case 3 doesn’t have a very steep knee, making it more difficult to differentiate cells from background: 
Case 3:
![barcodeRanks plot](https://user-images.githubusercontent.com/55449383/73136448-16a8a800-404e-11ea-9a01-57594ebb0a11.png)
```
set.seed(100)
called <- defaultDrops(new.counts, expected=9000)
table(called)
cell.counts <- new.counts[, called]
called
  FALSE    TRUE 
6792682    2198 
```
```
set.seed(100)
e.out <- emptyDrops(new.counts)
is.cell <- e.out$FDR <= 0.01
sum(is.cell, na.rm=TRUE)
[1] 73026
table(Limited=e.out$Limited, Significant=is.cell)
            Significant
Limited FALSE  TRUE
  FALSE  2020 17261
  TRUE      0 55765
```
![p-values distribution for empty droplets](https://user-images.githubusercontent.com/55449383/73136475-5a9bad00-404e-11ea-8fc1-16c3c75609ee.png)
![features_counts_MT](https://user-images.githubusercontent.com/55449383/73136492-7c952f80-404e-11ea-8850-a97c9ab9054c.png)

I’ve tried changing the lower () argument in emptydrops(), however I don´t know how much should I force it:
```
set.seed(100)
e.out <- emptyDrops(new.counts, lower=1000)
is.cell <- e.out$FDR <= 0.01
sum(is.cell, na.rm=TRUE)
[1] 2605
table(Limited=e.out$Limited, Significant=is.cell)
       Significant
Limited FALSE TRUE
  FALSE  1788  277
  TRUE      0 2328
```

As the number of mitochondrial genes is high (especially for case3), they may be the case you mentioned in which I captured pieces of cells inside the droplets. Apart for filtering those droplets to have less that 20% of mitochondrial genes, is the anything else I could do? Can I fine-tune anything else in DropletUtils to avoid continuing the analysis with such amount of “cells”?

Thanks a lot,

Lucía

**Comment by LTLA** [comment]
Some thoughts:

- Set the FDR threshold lower, e.g., to 0.1%. Probably won't change anything in this case but is good practice, 1% of cells being empty droplets is still pretty high if you think about it.
- Have a look at what `metadata(e.out)$retain` is, and make sure it makes sense. 
- Set `retain=Inf`, especially for case 3; this will ignore the knee point and call cells on their profiles alone. (The knee point forces all cells with higher totals to be retained.)
- Try removing the mitochondrial genes prior to cell calling. As in, call the cells on everything but the mitochondrial genes. (Maybe also ribosomal genes and other markers of damage.) This should reduce the differences between cell fragments and empty droplets and encourage removal.
- Construct a MA plot to see the differences in expression between the called libraries that are unlikely to be cells and the ambient profile, obtained from `metadata(e.out)$ambient`. This may provide some information about what is driving `emptyDrops()` to call these libraries as cells.
- Check against CellRanger 3's cell calls. It uses effectively the same algorithm so it would be interesting to see there are differences between their implementation and mine.

**Comment by LuciaJim** [comment]
Hi Aaron,
I've tried implementing the changes you recommend me. However I still have one question related with my previous message: In the histogram of the p-value distribution for the empty droplets, does the accumulation of high p-values (>0.8) mean that it would be good to increase the lower cutoff for the number of UMIs (>100)?

> - Set the FDR threshold lower, e.g., to 0.1%. Probably won't change anything in this case but is good practice, 1% of cells being empty droplets is still pretty high if you think about it.

For sure, lowering the FDR has helped to retain less low quality cells. Before I just followed the default percentage from the DropletUtils manual. However, as you foresaw, the number of what is consider a cell is still huge.

> - Have a look at what metadata(e.out)$retain is, and make sure it makes sense.

It makes sense with what the barcode ranks plot highlights as the inflection point.
```
metadata(br.out)$knee
metadata(e.out)$retain
```
Case1:
 ```
[1] 5496
[1] 5496
```
Case2:
 ```
[1] 4786
[1] 4786
 ```
Case3:
 ```
[1] 71139
[1] 71139
```
> - Construct a MA plot to see the differences in expression between the called libraries that are unlikely to be cells and the ambient profile, obtained from metadata(e.out)$ambient. This may provide some information about what is driving emptyDrops() to call these libraries as cells.

I've constructed the following MA plots:
```filtered.counts <- counts(sce)[,which(is.cell)]
cells <- calculateAverage(filtered.counts)
ambient <- calculateAverage(metadata(e.out)$ambient)
logged <- cpm(cbind(cells, ambient), log=TRUE, prior.count=2)
logFC <- logged[,1] - logged[,2]
abundance <- rowMeans(logged)
plot(abundance, logFC, xlab="Average count", ylab="Log-FC (cells/ambient)", pch=20)
is.mito <- grep("__MT-", rowData(sce)$Symbol)
points(abundance[is.mito], logFC[is.mito], col="dodgerblue", pch=20)
is.dead <- grep("CASP", rowData(sce)$Symbol)
points(abundance[is.dead], logFC[is.dead], col="orange", pch=20)
is.inflamatory <- grep("__TNF", rowData(sce)$Symbol)
points(abundance[is.inflamatory], logFC[is.inflamatory], col="yellow", pch=20)
plot(abundance, logFC, xlab="Average count", ylab="Log-FC (cells/ambient)", pch=20)
is.ribosomal1 <- grep("__RPS", rowData(sce)$Symbol)
points(abundance[is.ribosomal], logFC[is.ribosomal], col="green", pch=20)
is.ribosomal2 <- grep("__RPL", rowData(sce)$Symbol)
points(abundance[is.ribosomal], logFC[is.ribosomal], col="green", pch=20)
```
Case1:
![geneQC_MTblue_CASPorange_TNFyellow](https://user-images.githubusercontent.com/55449383/73662934-f5266c80-469c-11ea-9a0a-e62b4c9ad81e.png)
![geneQC_RIBgreen png](https://user-images.githubusercontent.com/55449383/73662942-f6f03000-469c-11ea-8448-b49593109969.png)

Case2:
![geneQC_MTblue_CASPorange_TNFyellow](https://user-images.githubusercontent.com/55449383/73665618-b21ac800-46a1-11ea-949f-6949d6db2147.png)
![geneQC_RIBgreen png](https://user-images.githubusercontent.com/55449383/73665623-b3e48b80-46a1-11ea-935e-29072017ac24.png)

Case3:
![geneQC_MTblue_CASPorange_TNFyellow](https://user-images.githubusercontent.com/55449383/73667242-4ab24780-46a4-11ea-979b-a9c41eda4f24.png)
![geneQC_RIBgreen png](https://user-images.githubusercontent.com/55449383/73667247-4be37480-46a4-11ea-8175-18437f22b63b.png)

I've read that each dot corresponds to a gene. Do you know how can I check what forms part of the considered ambient pool?

> - Try removing the mitochondrial genes prior to cell calling. As in, call the cells on everything but the mitochondrial genes. (Maybe also ribosomal genes and other markers of damage.) This should reduce the differences between cell fragments and empty droplets and encourage removal.

I've writen the following command line to try to get rid of those cells with more than 15% of mitochondrial genes before applying barcodeRanks and emptyDrops, however I didn't manage to obtain this pre-filtered data.
```
sce<-DropletUtils::read10xCounts("~/Solo.out/", col.names = TRUE)
class(counts(sce))
new.counts<-counts(sce)

# To identify the mitochondrial transcripts from a non-conventional animal species
is.mito <- grep("__MT-", rowData(sce)$Symbol)
# To compute mitochondrial QC metrics
sce.trial <- perCellQCMetrics(sce, subsets=list(Mt=is.mito))
sce.trial
qc.mitout <- sce.trial$subsets_Mito_percent > 15
sce.trial2 <- sce[,!qc.mito]
summary(qc.mito)
class(counts(sce.trial2))
```

> - Set retain=Inf, especially for case 3; this will ignore the knee point and call cells on their profiles alone. (The knee point forces all cells with higher totals to be retained.)

I've just used it for case3 as the other the knee point doesn't seem to be the problem for the other 2 samples.
 It seems that the results of retain=Inf and retain=visually where the knee is(~5000), give the same output of n_cells:
 ```
Default filters [1] 71139
retain=Inf [1] 60336
retain=5000 [1] 60339
```
as well as the same output in the gene distribution between cells and ambient (see MA plots from above).

Thank you for your time.

Best,
Lucía

**Comment by LTLA** [comment]
> In the histogram of the p-value distribution for the empty droplets, does the accumulation of high p-values (>0.8) mean that it would be good to increase the lower cutoff for the number of UMIs (>100)?

Not really. In fact, it would suggest that there are too many libraries with low, discrete counts that drive large p-values; I would guess that spike is formed by cell barcodes with a count of 1. You might consider removing, say, all libraries with counts below 10; perhaps something wonky is happening at very low counts, I don't know. 

Regarding the MA plots: my suggestion was to compare the ambient profile with droplets that are called but you don't think are cells, not against all cells. Nonetheless, there are some interesting features already from the plots you have shown. Like, what on earth are those genes that are so strongly "upregulated" in the ambient solution? I have never seen MA plots like these, I usually get a trumpet shape (see the Supps of the paper).

Regarding mitochondrial genes: I was referring to removal of mitochondrial genes (as in, literally subset out _the genes_ before using `emptyDrops()`), not to the removal of cells with high mitochondrial proportions.

**Comment by alexvpickering** [comment]
>  Try removing the mitochondrial genes prior to cell calling. As in, call the cells on everything but the mitochondrial genes. (Maybe also ribosomal genes and other markers of damage.) This should reduce the differences between cell fragments and empty droplets and encourage removal.

I found this to make a big difference for a sample with a similar UMI vs Rank profile. Setting `retain = Inf` had a minor effect, with or without removal of ribosomal/mitochondrial genes. Might be worthwhile adding a note to this effect in the docs?

**Comment by LTLA** [comment]
@alexvpickering Can you back that up with some plots/numbers/etc.? If you can, post them here (or better, make a new issue); I'd like to be able to refer people to something substantive.

**Comment by LuciaJim** [comment]
> Try removing the mitochondrial genes prior to cell calling. As in, call the cells on everything but the mitochondrial genes. (Maybe also ribosomal genes and other markers of damage.) This should reduce the differences between cell fragments and empty droplets and encourage removal.

I've also try applying this option, but in my case it didn't make a difference:
Default option
```
set.seed(100)
e.out <- emptyDrops(new.counts)
is.cell <- e.out$FDR <= 0.01
sum(is.cell, na.rm=TRUE)
[1] 73026
table(Limited=e.out$Limited, Significant=is.cell)
            Significant
Limited FALSE  TRUE
  FALSE  2020 17261
  TRUE      0 55765
```
`Retain=Inf` option
```
set.seed(100)
e.out <- emptyDrops(new.counts, retain=Inf)
is.cell <- e.out$FDR <= 0.001
summary(is.cell)
   Mode   FALSE    TRUE    NA's 
logical   13842   61204 6719834
```
Prior removal of mitochondrial genes
```
keep <- !row.names(new.counts) %in% unlist(mitochondrial_genes)
set.seed(100)
e.out <- emptyDrops(new.counts[keep, ])
is.cell <- e.out$FDR <= 0.001
summary(is.cell)
   Mode   FALSE    TRUE    NA's 
logical    3529   71517 6719834
``` 
The only thing that worked was carrying out the subsequent QC for min.features and maximum mitochondrial percentage.

**Comment by LTLA** [comment]
@LuciaJim As I said before, those MA plots are crazy. Have a look at Figure S2 of the Genome Biology paper, those are the types of MA plots I would be expecting. 

It would be unwise to call `cpm()` on the ambient proportions, those aren't counts anymore. I would instead suggest to create the MA plot from the averages from all retained cells versus all cells with `NA` p-values (i.e., the cells that were used to construct the ambient profile).

This should give you a more sensible MA plot for which it should be easier to identify genes that are potential troublemakers and might be worth filtering out.

**Comment by LuciaJim** [comment]
Hi Aaron,

It seems that the MA plots were not correctly done. I've used now the `edgeR::maPlot` option and this is what I obtain for the sample with a very low knee (case3):
```
filtered.counts <- counts(sce)[,which(is.cell)]
cells <- calculateAverage(filtered.counts)
ambient.cells <- which(is.na(e.out$FDR))
ambient <- rowSums(counts(sce)[, ambient.cells])
res <- maPlot(ambient, cells, normalize = TRUE)
```
![MAplot](https://user-images.githubusercontent.com/55449383/75034214-08af4100-54ad-11ea-9145-7d045d451336.png)

I've tried to highlight mitocondrial, apoptotic, inflamatory, ribosomal genes as before, however it didn't work. Can you please give me a hand? I tried the following things:
```

is.mito <- grep("__MT-", rowData(sce)$Symbol)
is.mito <- "dodgerblue"
res <- maPlot(ambient, cells, normalize = TRUE, col = is.mito)

is.mito <- grep("__MT-", rowData(sce)$Symbol)
colour <- rep("dodgerblue", length(is.mito))
res <- maPlot(ambient, cells, normalize = TRUE, col = colour)

# mitochondrial_genes is a list with mitochondrial gene names
colour <- rep('black', length(cells))
col[names(cells) %in% mitochondrial_genes] <- "dodgerblue"
res <- maPlot(ambient, cells, normalize = TRUE, col = colour)
```

**Comment by LTLA** [comment]
Regarding your MA plot: the most obvious thing is the bunch of high-abundance genes that are upregulated in your cells (i.e., negative log-fold changes in the ambient). What are they? Their systematic downregulation in the ambient solution is not consistent with uniform lysis.

Regarding `maPlot`: somehow you have managed to have an error in every single call.

> ```
> is.mito <- grep("__MT-", rowData(sce)$Symbol)
> is.mito <- "dodgerblue"
> res <- maPlot(ambient, cells, normalize = TRUE, col = is.mito)
> ```

Well, if you set `col=is.mito` and you set `is.mito="dodgerblue"`, then all points will be blue.

> ```
> is.mito <- grep("__MT-", rowData(sce)$Symbol)
> colour <- rep("dodgerblue", length(is.mito))
> res <- maPlot(ambient, cells, normalize = TRUE, col = colour)
> ```

Same as above, with the only difference being that you made a vector of blues.

> ```
> # mitochondrial_genes is a list with mitochondrial gene names
> colour <- rep('black', length(cells))
> col[names(cells) %in% mitochondrial_genes] <- "dodgerblue"
> res <- maPlot(ambient, cells, normalize = TRUE, col = colour)
> ```

Now black instead of blue. I don't know what you expect to do with the `col` assignment given that you never made a `col` variable in the first place.

**Comment by LTLA** [comment]
You may consider the discussion in #39 for some guidance.

**Comment by LuciaJim** [comment]
Hi Aaron, thank you for your time. I'm going to close this issue.

**Comment by LuciaJim** [comment]
Hi Aaron,

I revised the data and indeed your proposal about removing mitochondrial genes prior to cell call worked well, so I could get rid of the vast majority of broken cells. There was a problem with the nomenclature of the genes provided to unlist.
In my case, defining retain=Inf caused a huge difference in the amount of retained cells.

```
# without mitochondrial gene exclusion
set.seed(100)
e.out1 <- emptyDrops(new.counts)
is.cell1 <- e.out1$FDR <= 0.001
summary(is.cell1)
   Mode   FALSE    TRUE    NA's 
logical   3907   71139 6719834 
```

```
# without mitochondrial gene exclusion, retain=Inf
set.seed(100)
e.out2 <- emptyDrops(new.counts, retain=Inf)
is.cell2 <- e.out2$FDR <= 0.001
summary(is.cell2)
   Mode   FALSE    TRUE    NA's 
logical   14710   60336 6719834 

```

```
# with mitochondrial gene exclusion
keep <- !row.names(new.counts) %in% unlist(mito_genes)
set.seed(100)
e.out3 <- emptyDrops(new.counts[keep, ])
is.cell3 <- e.out3$FDR <= 0.001
summary(is.cell3)
   Mode   FALSE    TRUE    NA's 
logical   58412   16610 6719858 

```

```
# with mitochondrial gene exclusion, retain=Inf
#keep <- !row.names(new.counts) %in% unlist(mito_genes)
set.seed(100)
e.out4 <- emptyDrops(new.counts[keep, ], retain=Inf)
is.cell4 <- e.out4$FDR <= 0.001
summary(is.cell4)
   Mode   FALSE    TRUE    NA's 
logical   68428    6594 6719858 
```

**Comment by LTLA** [comment]
Good to hear. The `retain=` thing is perhaps not that surprising, its sole purpose is to ensure that we don't throw out high-count libraries that are probably cells but just happen to have similar expression profiles to the ambient solution. As long as the knee point detection looks sensible, I would have some faith in it.

I wonder if either you or @alexvpickering have publicly available datasets where you observe the mito effect on `emptyDrops()`, I'd like to put an example in the [book](http://bioconductor.org/books/devel/OSCA/).

**Comment by LuciaJim** [comment]
I don't have public datasets at this moment (neither in the near future), however I will let you know whenever they are available.
Thank you very much for your help.

**Comment by alexvpickering** [comment]
> I don't have public datasets at this moment (neither in the near future), however I will let you know whenever they are available.
> Thank you very much for your help.

same here
