### ISSUE TITLE
Output the read10xMolInfo into .csv

### ISSUE THREAD

**Issue by danmoore1987** [MarioniLab/DropletUtils#35]
Hi Aaron,

Great package!

I am a bit of a newbie to R. I am interested in looking at UMI duplication, how would i go about to export the `read10xMolInfo` output into a .csv and decoding the integer 2bit encoded values into ATCG? I basically want a .csv with a column of `barcode, umi, count, GeneName, EnselmbeID`.

Thank you! Oh also, thank you for all the tutorials, pretty much half the people i know have used them to learn how-to scRNA :)

**Comment by LTLA** [comment]
> how would i go about to export the `read10xMolInfo` output into a .csv

These molecule files are BIG. Even compressed, we're talking 100+ MB. Saving them as CSVs is not a good idea, I expect you'd get a ~1 GB file - what do you want to do with that? Excel is going to choke, and if you want to analyze it in R, you might as well read from the HDF5 file directly.

But, if I must give you instructions, you can just call `write.csv` on the output `DataFrame`:

```r
example(read10xMolInfo) # set up the example
info <- read10xMolInfo(out)
write.csv(info$data, file="blah.csv")
```

> decoding the integer 2bit encoded values into ATCG?

I don't have a function right now to do this, but again, why is this necessary for your purposes? The only thing I care about with UMIs is whether they are the same or not, and the integer codes are both sufficient and efficient for that comparison. I could perhaps imagine that you would need this conversion if you care about the UMI sequence composition, but this seems like a stretch...

> Oh also, thank you for all the tutorials

My pleasure.

**Comment by danmoore1987** [comment]
Thank you for the prompty reply!
I am looking into the uneveness of PCR amplification across genes (heaps of bias) which is why i am interested in looking at UMI duplication.
I want to write it out into .csv format as I am uncomfortable with the structure of .h5 (newbie to coding). I was just going to parse out ~20 genes and some house keeping genes so size isn't that much of a problem. 
I figured that you can decode it by using a modulo operator...but i was hoping you have already looked into it at one point so have a script lying around :) 

All good! Thanks again!

**Comment by LTLA** [comment]
That's fine and all, but as I said, you don't _need_ the literal base sequence of the UMI. There is no need to decode the UMI sequence, all you need to know is that the integer codes with the same value represent the same UMI.

**Comment by LTLA** [comment]
I'll assume that this is resolved.

**Comment by wook2014** [comment]
I faces the same problem and I find out that to convert umi from 10 based number to ATCG should do a number base conversion from 10 based to 4 based and it will meet up with description in 
`https://software.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/molecule_info`
as it described in 10x official docs:
```
The UMI sequences are 2-bit encoded as follows:

Each pair of bits encodes a nucleotide (0="A", 1="C", 2="G", 3="T").
The least significant byte (LSB) contains the 3'-most nucleotides.
```
