### ISSUE TITLE
Output Downsampled Reads Matrix

### ISSUE THREAD

**Issue by mhwadsworth91** [MarioniLab/DropletUtils#37]
Hello,

First off, thank you so much for providing rigorous documentation for this R package; I've found this package to be incredibly useful for handling 10x datasets. 

At your earliest convenience, I would greatly appreciate your advice on a specific DropletUtils function. Currently, I'm implementing the function 'downsampleReads' to obtain a downsampled UMI matrix that will allow me to properly benchmark my sample, processed with 10x V3 chemistry, against the same sample processed with Drop-Seq S^3 (second strand synthesis, updated protocol). While your function provides a downsampled UMI matrix, I'm wondering if there's a way to also output a downsampled Reads matrix? This way, I could doublecheck that my 10x downsampled dataset is at the same read depth as the Drop-Seq S^3 dataset I'm benchmarking against.

Thank you for your time.

**Comment by LTLA** [comment]
> While your function provides a downsampled UMI matrix, I'm wondering if there's a way to also output a downsampled Reads matrix?

There is a pretty easy way of getting the reads without any code modification on my end.

1. Use `read10xMolInfo` to pull in the gene, cell and read count.
2. Use `makeCountMatrix` to make a sparse matrix by passing along those three vectors.
3. Use `downsampleMatrix` to downsample that sparse matrix, using the same parameters in `downsampleReads` (note the differences in the `bycol` defaults).

Alternatively, I could change one line in `downsampleReads` that would do the same thing. But I don't really get the point of doing so, the read coverage seems irrelevant if you have the same number of UMIs. If you just want to double-check the internals, just `debug(downsampleReads)`, run the function and check that `sum(new.read.counts)` is what you wanted it to be.

**Comment by mhwadsworth91** [comment]
Thank you, Aaron! I appreciate your help.
