### ISSUE TITLE
downsampleReads on Feature Barcoding data?

### ISSUE THREAD

**Issue by ageretz** [MarioniLab/DropletUtils#44]
Hello,

Is there a way to specify different proportions for different rows in downsampleReads? We have data that contains gene expression plus feature barcoding (generated by cellranger count 3.0) but some of the feature barcoding runs were from different sequencing runs. So we don't necessarily want to specify the same proportion for the gene and protein features.

I know we can also do downsampleMatrix and handle the feature barcoding and gene expression matrices separately, but because the documentation notes "Technically, downsampling on the reads with downsampleReads is more appropriate as it recapitulates the effect of differences in sequencing depth per cell" we thought we'd also check out downsampleReads.

Thank you!  I apologize if I am overlooking something but I did not see this in the documentation.

**Comment by LTLA** [comment]
Sounds reasonable. See the `features=` argument in 1.9.2.

As with most things that are technically correct, it probably doesn't matter if you use `downsampleMatrix` instead. In fact, `downsampleMatrix` will at least guarantee that the UMI counts are scaled down by the specified amount, whereas there is no such guarantee for `downsampleReads` (as this depends on the read:UMI ratio).
