### ISSUE TITLE
Different results in emptyDrops() depending on test.ambient

### ISSUE THREAD

**Issue by frederikziebell** [MarioniLab/DropletUtils#49]
I get different results for the number of significant barcodes depending on how `test.ambient` is set. Here's an example:

```
fdr <- .001
lower <- 100
set.seed(0)
my.counts <- DropletUtils:::simCounts()
set.seed(0)
out <- emptyDrops(my.counts, lower=lower)
set.seed(0)
out.ambient <- emptyDrops(my.counts,test.ambient=T, lower=lower)

sum(out$FDR<fdr & out$Total>lower)
# 901
sum(out.ambient$FDR<fdr & out.ambient$Total>lower)
# 801
```

The documentation for `test.ambient` says whether results for barcodes with totals less or equal to `lower` should be reported, so the number of significant barcodes with totals above `lower` should be the same. Am I missing something?

**Comment by LTLA** [comment]
The FDR adjustment has to account for more barcodes when you include everything below `lower`, so that usually drags the number of significant barcodes down (given that most of the newly included barcodes will not be significant).

**Comment by LTLA** [comment]
The most recent version of the package will now omit the assumed-empty droplets from the FDR correction even if `test.ambient=TRUE`, so you should be able to get the same results (provided you set the same seed). If you want to retain the existing behavior, you can set `test.ambient=NA`, which will include the empty droplets in the correction as before.
