### ISSUE TITLE
downsampleReads error

### ISSUE THREAD

**Issue by snowballdbs** [MarioniLab/DropletUtils#50]
Can't run downsamplereads or read10xMolInfo on my h5 file. I have tried using different versions of DropletUtils (including most up to date) in in both R 4.0.2 and R 3.6.1.  In most cases (besides v1.9) can get example script to run. See my script below. Any help would be appreciated.  I attached error code for this particular trial but sometimes running the same exact script I get the error. 

"Error in read10xMolInfo(sample, barcode.length, get.umi = FALSE) : 
  c++ exception (unknown reason)" 

10x info is as follows Chemistry | Single Cell 3' v3         Pipeline Version | 3.1.0

######################Script############################
library(DropletUtils)
#DropletUtils v1.6.1
#R version 4.0.2 (2020-06-22)
out <- "Z:\\Bioinformatics\\Students_Fellows\\Snowball\\pctc\\Normal_Human_Epi_Mes\\Cellranger\\hg38\\filtered_feature_bc_matrix.h5"
read10xMolInfo(out)
hg38_downsample <- downsampleReads(out, prop=.2, barcode.length=NULL, bycol=FALSE)

#############Example Script that works############
out <- DropletUtils:::sim10xMolInfo(tempfile(), nsamples=1)
# Downsampling by the reads.
out2 <- downsampleReads(out, barcode.length=0, prop=0.5)

##############Error######################

> hg38_downsample <- downsampleReads(out, prop=.2, barcode.length=NULL, bycol=FALSE)
: Symbol table
    minor: Callback failed
  #005: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'barcode' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5D.c line 298 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Dint.c line 1410 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'barcode' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5D.c line 298 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Dint.c line 1410 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'barcode' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5D.c line 298 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Dint.c line 1410 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'barcode' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5D.c line 298 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Dint.c line 1410 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: C:/rtools40/tmp/CMake-hdf5-1.10.6/hdf5-1.10.6/src/H5Gtraverse.c line 851 in H5G_traverse(): Error in read10xMolInfo(sample, barcode.length, get.umi = FALSE) : 
  c++ exception (unknown reason)
> hg38_downsample <- downsampleReads(out, prop=.2, barcode.length=NULL, bycol=FALSE)
Error in read10xMolInfo(sample, barcode.length, get.umi = FALSE) : 
  c++ exception (unknown reason)

**Comment by LTLA** [comment]
CellRanger produces two HDF5 files. One is the molecule information file, the other is the HDF5-formatted matrix. (Well, technically there are three files, counting the filtered and raw matrices.)

`downsampleReads()` and `read10xMolInfo()` expect the molecule information file, but you seem to have given it the filtered HDF5 matrix file. Hence the errors.

**Comment by snowballdbs** [comment]
Definitely overlook this. That is probably the issue. I will adjust and re-run.
