### ISSUE TITLE
'Cannot find cells provided' with Seurat object

### ISSUE THREAD

**Issue by Firedrops** [MarioniLab/DropletUtils#51]
The error message
```
Warning: The following arguments are not used: drop
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided
```

[pbmc5k dataset](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.2/5k_pbmc_v3), I have tried both the raw and filtered datasets.

Preceding code
```
pbmc.data <- Read10X(data.dir = "data/pbmc5k/raw_feature_bc_matrix/")

pbmc_raw <- CreateSeuratObject(counts = pbmc.data, project = "pbmc5k", min.cells = 3, min.features = 200)

pbmc_raw[["percent.mt"]] <- PercentageFeatureSet(pbmc_raw, pattern = "^MT-")
```
I have also tried without `min.cells = 3, min.features = 20`, to no avail.

Calling EmptyDrops

```
emptyDrops(
  pbmc_raw,
  lower = 100,
  niters = 10000,
  test.ambient = FALSE,
  ignore = NULL,
  alpha = NULL,
  BPPARAM = SerialParam()
)
```
Similarly, I have tried `testEmptyDrops`, only to receive the same error.

RStudio Version 1.3.1056
Seurat_3.2.0 
DropletUtils_1.6.1

Does anyone know why it's not working, and/or how I could get around the error?

**Comment by LTLA** [comment]
Sounds like a **Seurat** problem to me. I don't see what `emptyDrops()` has to do with it.

**Comment by Firedrops** [comment]
My bad, still new to this and it hasn't occurred to to me that Seurat isn't 'universally' used. Will read the vignette again and try other data formats.
