### ISSUE TITLE
Execution speed of emptyDrops and estimateAmbience

### ISSUE THREAD

**Issue by ycl6** [MarioniLab/DropletUtils#55]
The speed of running both `emptyDrops` and `estimateAmbience` is very slow if the count matrix input is a `DelayedMatrix` or `TENxMatrix` object. 

I understand the documentation did mentioned the expected input is either a `dgTMatrix` or `dgCMatrix`. However, as `read10xCounts` also works with a HDF5 input and stores counts as `DelayedMatrix`,  it will be great if the functions are also *DelayedArray-friendly*, maybe a check on the object class and convert to `dgCMatrix` if necessary at the beginning of the operation?

**Comment by LTLA** [comment]
Yes, that would be a good idea. 

One problem is that `emptyDrops()` does not parallelize some of the parts that would need to be parallelized for file-backed matrices; however, for `alpha = NULL`, it turns out I need to realize it into memory anyway, so I might as well just do that.
