### ISSUE TITLE
how to determine parameter "lower" in emptyDrops function. 

### ISSUE THREAD

**Issue by hk20013106** [MarioniLab/DropletUtils#57]
Hi, I'm using the BD Rhapsody scRNA technique.  We sequenced 100G data for one sample and obtained maybe 9000 nuclei (not cell). 

I'm using the only output matrix which I assume is the raw (I'm not 100% sure [upate: this is NOT correct, see my next comment]). The knee and inflection are 326 and 144, respectively (following this tutorial https://bioconductor.org/packages/release/bioc/vignettes/DropletUtils/inst/doc/DropletUtils.html) 

When using the default value in emptyDrops (lower = 100), no output obtained as mentioned here (https://github.com/MarioniLab/DropletUtils/issues/29). Apparently, because no ambient exists ( colSum < 100). 

I change the "lower" to 150 or 200 which works well. But the results are different. 
For example, when using 150, the cell number is 8670, and empty is 1187; when using 200, the cell number is 7232, empty 2197 and NA 436. 

I understand that "lower" is the total umi per nuclei in my case, but not sure how can I decide this parameter since it highly affects the result? 

Thank you very much!

![image](https://user-images.githubusercontent.com/5851110/107998768-cfbc8600-6fb3-11eb-8afb-1a1d762faff1.png)

_Originally posted by @hk20013106 in https://github.com/MarioniLab/DropletUtils/issues/29#issuecomment-779450589_

**Comment by LTLA** [comment]
This does not look like unfiltered data. I'm not familiar with the BH Rhapsody system, but if you look at plots generated from 10X data, you'll see an inflection and then a plateau towards zero on the right side of the plot. These represent empty droplets that are used to estimate the ambient RNA profile. Your data doesn't seem to have this, so there is no way to estimate the ambient profile.

The default `lower=100` would probably have been a sensible choice if you did have unfiltered data, but you don't, so there's not much that can be done here.

**Comment by hk20013106** [comment]
Thank you very much for your quick reply.

I just look into the raw data, and found an "RSEC_MolsPerCell_Unfiltered.csv" file which I completely forgot.  I apologize for my carelessness. 
In case someone else using BD might be interested, I post the information here.
