### ISSUE TITLE
Error when using `read10xCounts`

### ISSUE THREAD

**Issue by msto** [MarioniLab/DropletUtils#7]
Hi,

I'm encountering the following error when trying to use the `read10xCounts` function.

```
> library(DropletUtils)
> fname <- "data/pbmc4k/"
> list.files(fname)
[1] "barcodes.tsv" "genes.tsv"    "matrix.mtx"
> sce <- read10xCounts(fname, col.names=TRUE)
Error in `rownames<-`(`*tmp*`, value = c("ENSG00000243485", "ENSG00000237613",  :
  invalid rownames length
```

I stepped through the function by hand and the error seems to occur in the final line, when constructing the SingleCellExperiment object. I had trouble finding the line that might be causing it in the SCE codebase; is this an error you've seen before, or do you know what might be causing it?

I'm using R 3.5.1, DropletUtils 1.2.1, and SingleCellExperiment 1.4.0. I'm observing this error in several of the publicly available 10X datasets, including the [10X PBMC 4k](https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/pbmc4k) dataset that was used in the EmptyDrops paper.

Thanks!

Matt

**Comment by LTLA** [comment]
This should work fine, see an example [here](http://bioconductor.org/packages/release/workflows/vignettes/simpleSingleCell/inst/doc/work-3-tenx.html). Make sure all of the other packages are correct with `BiocManager::valid()`; as a lost resort, re-install all dependent packages, as recommended [here](https://support.bioconductor.org/p/101813/#102033).

**Comment by msto** [comment]
Ok, I removed and re-installed all packages and it's working now. Thanks, sorry to bother you.
