### ISSUE TITLE
emptyDrops was stuck when applying to filtered data

### ISSUE THREAD

**Issue by shenyang1981** [MarioniLab/DropletUtils#8]
Hello,

I was trying to identify droplets on filtered data in which only barcodes with at least 100 nUMI were kept. The emptyDrops got stuck and never ended. I am curious if the input must be original count matrix from 10X rather than filtered one. Thanks for your help.

Best,
Yang

**Comment by LTLA** [comment]
Yes, the input should be the original count matrix. If you apply it on that filtered matrix, there won't be anything to estimate the ambient proportions with. I don't know why it would get stuck - it should just report a whole stack of `NA` results - but in any case, your inputs are not what it expects.

**Comment by shenyang1981** [comment]
Thanks for replying. Now I understand that I should not apply it to public filtered data. BTW, for our in-house data, as ~50% barcodes contain less than 10 nUMI in the original matrix, I have also tested this method for mildly filtered matrix ( >= 10 nUMI), the results seem to be very similar. I am curious if this is accepted since it would reduce the memory usage and computational time. 

Best,
Yang

**Comment by LTLA** [comment]
You will reduce the precision of the ambient pool estimation, as you're throwing away 50% of your barcodes - probably around 100,000? - that contain some information about the ambient pool. I would leave them in; they are so sparse that memory is not a real issue, and they will only be used during an initial `rowSums` and `colSums` so the time spent processing them will not be noticeable compared to the Monte Carlo calculations.
