### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SaraJeanne08** [MarioniLab/DropletUtils#83]
Hi - I tried installing via github_install and got the following error. I tried updating the corresponding packages but still get the following error:

installing to /efs/home/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-DropletUtils/00new/DropletUtils/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘ROWNAMES<-’ is not exported by 'namespace:S4Vectors'
Execution halted
ERROR: lazy loading failed for package ‘DropletUtils’
* removing ‘/efs/home//R/x86_64-pc-linux-gnu-library/4.0/DropletUtils’
* restoring previous ‘/efs/home/R/x86_64-pc-linux-gnu-library/4.0/DropletUtils’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpXYbujq/file27e57f5c33c7/DropletUtils_1.15.3.tar.gz’ had non-zero exit status

I do not get the newest version 1.15.2 when installing/ updating via Bioconductor - because emptyDropsCellRanger function doesn't exist post update (bioconductor still has 1.14.2 listed). Thank you for helping get the newest version of DropletUtils for this function. Thank you!

**Comment by jonathangriffiths** [comment]
Hi Sara,

Looks like you're running R 4.0 from your package install path - is that right? This only supports Bioconductor up to version 3.12. The current devel builds are preparing for Bioc 3.15. If you updated packages using BiocManager, they will only be updated to whatever they were in Bioc 3.12, not to what they need to be in Bioc devel for the very latest version of this package.

If you really need the very latest version of DropletUtils, it would be best to install Bioc devel - that way you will have access to the devel versions of all dependencies. https://www.bioconductor.org/developers/how-to/useDevel/

Cheers
Jonny

**Comment by JovannyChen** [comment]
How did you solve this error, finally? I met the totally same error.

**Comment by jonathangriffiths** [comment]
You probably have package version incompatibility issues. I would update to R 4.2, install Bioconductor 3.15, and then go from there.

**Comment by harshini-c** [comment]
Hi,

I am having the same issue while installing. I have R 4.2.0 and bioconductor 3.15, and i still get error. 

Please see the attached image if it is useful.

Can you let me know how to resolve this issue? 

Thank you!

<img width="593" alt="image" src="https://user-images.githubusercontent.com/78223419/179081835-0b0f8166-52a0-451b-aaa3-d3723f354095.png">
