### ISSUE TITLE
Aberant number of cells

### ISSUE THREAD

**Issue by GregoireDS** [MarioniLab/DropletUtils#85]
Hi ! 

I've tried to compare the output from Cellranger 3.0 with DropletUtils::emptyDrops() in term of number of cell-containing droplets. The web-summary from the Cellranger run outputs 1240 cells which is indeed very consistant when looking at the UMI Vs ranked-barcodes plot (the drop of the curve is around the 1100-1300th barcode). It is far less than I expected with regard to the number of cells I've put as input but this could be explain by some technical reasons I guess (wrong cell counting, bad cell lysis).

1/ However when running DropletUtils::emptyDrops() on the unfiltered Cellranger matrix.h5, I obtain very high number of cell-containing barcodes (15307 !!). This is with default parameters but I've tried to adjust and it doesn't change anything (see following code). How comes that DropletUtils::emptyDrops() outputs so different numbers than cell ranger 3.0? What should I do? 

2/ Also it takes +/- 4h for DropletUtils::emptyDrops() to run on my sample, even with BPPARAM option. Any suggestion? 

Thanks a lot ! 

R CODE : 

sce <- read10xCounts("/Users/Gregoire/Desktop/Dowloaded_from_cluster/count/raw_feature_bc_matrix.h5", col.names=T)
sce
_#CASE 1 use emptyDrops with default parameters : it will retain every cells above knee of UMI Vs ranked-barcode plot_ 
counts <- counts(sce)
tic()
set.seed(100)
e.out.1 <- DropletUtils::emptyDrops(counts,BPPARAM = SerialParam())
summary(e.out.1$FDR < 0.001)
sum(e.out.1$FDR <= 0.001, na.rm=TRUE)
toc()

**# RESULT = 15307**

_#CASE 2 use emptyDrops with retain=inf: it will retain every cells above inflection point of UMI Vs ranked-barcode plot_ 
tic()
set.seed(100)
e.out.2 <- DropletUtils::emptyDrops(counts, retain = Inf)
summary(e.out.2$FDR < 0.001)
sum(e.out.2$FDR <= 0.001, na.rm=TRUE)
toc()

**# RESULT = 15307**

_#CASE 3 use emptyDrops on counts matrix without ribosomal or mitochondrial genes that could be captures in non-cell-containing drops_
qc <- list(Mito = grep("^MT-",rowData(sce)$Symbol),
           Ribo = grep("^RPS",rowData(sce)$Symbol)
           )
keep <- !row.names(counts) %in% unlist(qc)

tic()
set.seed(100)
e.out.3 <- DropletUtils::emptyDrops(counts[keep, ])
summary(e.out.3$FDR < 0.001)
sum(e.out.3$FDR <= 0.001, na.rm=TRUE)
toc()

**# RESULT = 15307**

_#CASE 4 use emptyDrops with lower =200 : in case the knee is artificially put in small bump of the curve at high ranked-barcode position_
tic()
set.seed(100)
e.out.4 <- DropletUtils::emptyDrops(counts,lower =200)
summary(e.out.4$FDR < 0.001)
sum(e.out.4$FDR <= 0.001, na.rm=TRUE)
toc()

**# RESULT = 5960**

**Comment by jonathangriffiths** [comment]
Hi there.

A couple of points from me:

- This sort of question is really better served on the Bioconductor support site rather than as an issue on the codebase. Check out [help.bioconductor.com](https://support.bioconductor.org)
- When you have set `BPPARAM = SerialParam()`, you've actually asked your code to run on a single core only. You need to use one of the multicore param options here (e.g. `MulticoreParam`)

As regards your problem, I suspect Aaron will know better, but I would imagine that the knee point is being identified in the wrong place. It is typically useful to visualise your data to identify these sorts of problems (e.g. in a similar manner to the cellranger output).

Jonny

**Comment by GregoireDS** [comment]
Hi ! 

Thanks a lot for your quick reply. 
I will transfer my question to the bioconductor support, sorry if it was misdirected. 

Indeed I suspect the knee point to be identified in the wrong place too because in the #CASE4 in which I provided a lower limit, the number of cell-based barcodes decreased. However I do not know how to attribute a robust threshold that is not to be provided by the user based on a-priori or graph. 

Thanks again,

Grégoire
