### ISSUE TITLE
Feature request: Port 'Support version 3 format files in read10xCounts' to release

### ISSUE THREAD

**Issue by PeteHaitch** [MarioniLab/DropletUtils#9]
Would this be difficult?
I've got some samples processed with **CellRanger** v3 (`barcodes.tsv.gz`, `features.tsv.gz`, `matrix.mtx.gz`), which the version of `read10xCounts()` in the release branch can't handle.
Unfortunately, I can't switch to devel because IT reasons.
For now, I've just worked around it by copying the relevant code to a local script, but it'd be cool to have since there's a few months yet until devel becomes release.

**Comment by LTLA** [comment]
Ugh. Porting would be a real pain. You can't just `remotes::install_github`? I removed the R version requirement for that reason, I imagined people would complain like this.

**Comment by PeteHaitch** [comment]
Ah cool, I didn't try that because I was expecting impossible dependencies.
But that stop-gap works for me.
