### ISSUE TITLE
Using removeSwappedDrops for cellranger reanalysis output (without molecule_info.h5) 

### ISSUE THREAD

**Issue by ayumatsubo** [MarioniLab/DropletUtils#93]
I used `cellranger reanalyze` protocol (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_ra) and `cellranger reanalyze` output does not  include `molecule_info.h5`. 

I tried to use `removeSwappedDrops` function, but I did not know what to set for inputs.

If I set for inputs as `molecule_info.h5` from `cellranger count` for `swappedDrops`, it may output the matrix that did not process by `cellranger reanalyze`, right?

I want to set for inputs as `read10xCounts(filtered_feature_bc_matrix)` for `removeSwappedDrops`, but I do not know `umis, genes, nreads` in the SCE object.

Is there any solution after `cellranger reanalyze` to use `SwappedDrops`?

Thank you for advance.

**Comment by jonathangriffiths** [comment]
Hi,

The `cellranger reanalyze` commands apparently only:

> reruns secondary analysis performed on the feature-barcode matrix (dimensionality reduction, clustering, and visualization) using different parameter settings.

This implies to me that there is no change to the underlying data (count matrix) between your `cellranger count` and `reanalyze` run. Assuming you are going to be doing QC, dimensionality reduction etc. yourself, you should have no need for the `reanalyze` output for your swappedDrops analyses, and should be safe to use the count matrix from `cellranger count`.

Jonny
