### ISSUE TITLE
umi.min.frac.median Parameter bugs

### ISSUE THREAD

**Issue by Liripo** [MarioniLab/DropletUtils#94]
https://github.com/MarioniLab/DropletUtils/blob/3eced74482c67fc372265c27e86addd5407d75e7/R/emptyDropsCellRanger.R#L135-L144
Hi developer,:
    In line 144 of the code above, you don't sort the  `totals` variable, I think it is a bug?
![image](https://user-images.githubusercontent.com/54770415/202854105-9c37f6b4-51a9-4a3a-8a27-04fd255022f8.png)
Thanks!

**Comment by LTLA** [comment]
Tagging @DongzeHE. From a brief inspection, it seems that there may be an issue. 

Fix should be simple, at the cost of a few extra lines:

```
ordered.totals <- totals[order(totals, decreasing = TRUE)]
n.umi.max <- ordered.totals[min(length(totals), max.ind)] # nUMImax 

# .... etc.

simple.totals <- head(ordered.totals, ncells.simple)
min.umi  <- max(umi.min, round(umi.min.frac.median * median(simple.totals)))
```

**Comment by DongzeHE** [comment]
Hi all,

This is totally my mistake! I have started a PR to resolve this issue. 


 Best,
Dongze
