### ISSUE TITLE
Large peak near 1 when examining cell-calling diagnostics

### ISSUE THREAD

**Issue by fluentin44** [MarioniLab/DropletUtils#99]
Hi, 

Im calling empty drops with below code, but when plotting a histogram of p values get a large peak near 1. I understand a peak near zero what is the significance of a peak near 1?

`set.seed(100)
limit <- 100   
all.out <- emptyDrops(counts(drop_seq_counts), lower=limit, test.ambient=TRUE)
hist(all.out$PValue[all.out$Total <= limit & all.out$Total > 0],
    xlab="P-value", main="", col="grey80") `

![Rplot](https://user-images.githubusercontent.com/49235414/224285482-a8a556b1-f9fb-48c7-b24c-6fc2996bf756.png)

Thanks, 
Matt

**Comment by LTLA** [comment]
If I had to guess, I'd say that is a consequence of discreteness. Some droplets with low counts don't have much choice in their p-values, so they just clump up at one place. The rest of the distribution looks uniform so it seems that the ambient profile is okay; as long as it's holding its size at low p-values (i.e., `mean(ambient.pvalue <= 0.05)` is close to 0.05, and so on for other low choices of a significant threshold), oddities at high p-values don't really matter.

**Comment by fluentin44** [comment]
Great ok, with the below im getting ~0.023, does that seem close enough?

`mean(all.out$PValue[all.out$Total <= 100 & all.out$Total > 0 & all.out$PValue <= 0.05])`

And apologies on piggy-backing but I dont understand the relationship between calling the barcoderank plot and empty drops - is the knee indicated on the barcode plot an indication of how emptydrops may act?

Also is there an explicit function / is it necessary to run barcode plots per sample? Below is for the whole dataset. 

![ss_barcode_plot](https://user-images.githubusercontent.com/49235414/224683556-07b32d6e-792e-455d-9a5a-b12c6d6579f6.png)

Thanks, 
Matt

**Comment by LTLA** [comment]
More like

```r
mean(all.out$PValue[all.out$Total <= 100 & all.out$Total > 0] <= 0.05)`
```

> is the knee indicated on the barcode plot an indication of how emptydrops may act?

Everything above the knee is treated as a cell regardless of the `emptyDrops` p-value. For stuff below the knee (but above the threshold of 100), the calls depend on the p-value.

> Also is there an explicit function / is it necessary to run barcode plots per sample? Below is for the whole dataset.

Doesn't make a lot of sense to run it on multiple samples at once, because all the curves mush together. If you're planning to make diagnostic plots, it's better to generate these per sample. You throw multiple curves on the same plot if you like.

**Comment by fluentin44** [comment]
Much appreciated - mean p = 0.055. 

Great, thanks for the help.
